# Generated by Django 4.1.9 on 2023-05-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoilMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ph_value", models.FloatField()),
                ("npk_values", models.CharField(max_length=255)),
                ("coordinates", models.CharField(max_length=255)),
                ("measurement_date", models.DateTimeField()),
            ],
        ),
    ]
