# Generated by Django 4.1.9 on 2023-06-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0002_remove_soilmeasurement_coordinates_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fieldLength", models.FloatField(default=0.0)),
                ("fieldWidth", models.FloatField(default=0.0)),
                ("numberOfReadings", models.IntegerField(default=0)),
            ],
        ),
    ]
